### ISSUE TITLE
Update Alarm Func

### ISSUE THREAD

**Issue by jks5177** [aivle-SDG21/MiniProject1-DjangoWebApp_n#24]
### member > views.py
`def alarm(request)` : post.subject 추가해서 데이터 전송
`def click_alarm(request)` : 알람 버튼 클릭 시 알람 데이터 전송(comment data, post_subject가 전송)
`def my_paper(request)` : Paginator 5 -> 3

### member > templates > member
`_post_card.html` : 알람 데이터가 입력 후 출력 html
`index.html` : _post_card.html을 layout에 상속

**Comment by aivle-SDG21** [comment]
고생하십니다. ㅠㅠ
