### ISSUE TITLE
Update Memo with Authorization

### ISSUE THREAD

**Issue by Gnadi4** [aivle-SDG21/MiniProject1-DjangoWebApp_n#28]
<<memo>>

#model.py

user 필드 추가 , 현재 로그인 되어있는 유저의 아이디 저장

text 필드에 black=True 설정 - 빈 메모를 저장할 수 있음

#view.py

def memo : 현제 로그인 되어있는 유저의 아이디를 DB에서 조회하여 form에 뿌려주고 이전에 DB에 남아있는 내용을 삭제한다 (유저 1명은 1개의 메모만 가질 수 있다)

**Comment by aivle-SDG21** [comment]
👍👍👍👍👍
