### ISSUE TITLE
main update

### ISSUE THREAD

**Issue by codebottlehun** [aivle-SDG21/MiniProject1-DjangoWebApp_n#30]
#### Search 기능을 강화하였습니다.
이전에는 현재 url에 query값을 날렸지만, 앞으로는 어떠한 page라도 codagram url로 query를 날립니다.

#### Post_list가 강화되었습니다.
10개씩 끊어서 출력하고 스크롤을 아래로 내릴 시에 비동기 형식으로 남은 값을 가져옵니다.
마지막 페이지에 도달하였을 때 맨 마지막에 No more data를 알려주고 더 이상 값을 가져오지 않습니다.
검색을 해도 해당 동작은 동일하게 작동합니다.

**Comment by aivle-SDG21** [comment]
Pull 뒤에 동작확인하였습니다.
