### ISSUE TITLE
My Page Func Delete

### ISSUE THREAD

**Issue by jks5177** [aivle-SDG21/MiniProject1-DjangoWebApp_n#9]
member > views.py
`def delete` : 글 삭제 기능(mypage에서 del 버튼 사용)
`def alarm` : 알람 Table의 사용자에 해당하는 데이터 return
`def search` : Inpu-검색어, Outpu-검색어 포함 데이터 / 검색어를 공백 문자로 나눈 후 포함되는 subject 데이터 출력

[ ] : `def alarm`과 `def search`는 테스트해보지 못했습니다.

[ ] : Post와 Commemt Table은 post App에 있는 Model로 전부 수정했습니다.

**Comment by aivle-SDG21** [comment]
고생하셨습니다.
